version: "3.9"

services:
  postgres:
    image: postgres:latest
    hostname: postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "wb_app"
      POSTGRES_USER: "service"
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U service -d wb_app"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  nats-js:
    image: nats:latest
    hostname: nats

    command:
      - "-js"
    ports:
      - "4222:4222"
      - "8222:8222"

    restart: unless-stopped
  service:
    build: .
    ports:
      - "8081:8081"

    depends_on:
      - nats-js
      - postgres

volumes:
  pg_data:
