version: 3

# Позволяет подгрузить переменные окружения, что нужны для работы сервиса
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  run:
    cmds:
      - ./app
    desc: "Starts the L0 service"
  build:
    cmds:
      - go build -o app cmd/service/app.go
    desc: "Builds the service"

  migrate:
    cmds:
      - ./bin/migrate -database {{.CON_SCHEMA}} -path db/migrations {{.action}}
    desc: "Applies the migrations on postgres server"
